MakingUsers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Users.urls'), name="Users"),
    path('admin/', admin.site.urls),
]

Users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'Users'

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),



]

Users/models.py
from django.db import models

# Create your models here.

Users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout

def home(request):
    return render(request, 'Users/home.html')

def signup_view(request):
    if request.method == 'POST': #If the user is creating a post, if the user already exist cause error, otherwise create the user form
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('Users:home')
    else:
        form = UserCreationForm()
    return render(request, 'Users/signup.html', {'form': form})


def login_view(request): # Log the user in if authentication comes back true
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next')) #Continue onto page previously requested
            else:
                return redirect('Users:home')
    else:
        form = AuthenticationForm()
    return render(request, 'Users/login.html', {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("Users:home")

Users/templates/Users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>
    <nav>
        <a href="{% url 'Users:login' %}">Login</a>
        <a href="{% url 'Users:signup' %}">Sign Up</a>
        <a href="{% url 'Users:logout' %}">Logout</a>
    </nav>
    <h1>Welcome to the home screen</h1>
    {% block content %}
    {% endblock %}
</body>
</html>

Users/templates/Users/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'Users:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>

{% endblock %}

Users/templates/Users/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>

{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <nav>
        <a href="{% url 'Users:login' %}">Login</a>
        <a href="{% url 'Users:signup' %}">Sign Up</a>
        <a href="{% url 'Users:logout' %}">Logout</a>    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>